HelloWorld/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello_world/', include('hello_world.urls')),
]

account/urls.py
from django.urls import path

from account.views import(
	account_view,
	edit_account_view,
	crop_image,
)

app_name = "account"

urlpatterns = [
	path('<user_id>/',account_view,name='view'),
	path('<user_id>/edit/',edit_account_view,name='edit'),
	path('<user_id>/edit/cropImage',crop_image,name='crop_image'),
]

chat/urls.py
from django.urls import path,include

from . import views

app_name = 'chat'

urlpatterns = [
	path('private/chat/<int:receiver_id>/',views.private_chat,name='private_chat'),
	path('group/',views.create_group,name='create_group'),
	path('group_view/<int:chat_id>/',views.group_view,name='group_view'),
    path('<int:chat_id>/',views.room,name='room'),
]

web_chat/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from personal.views import (
	home_screen_view
)
from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls',namespace='account')),
    path('friend/',include('friend.urls',namespace='friend')),
    path('chat/',include('chat.urls',namespace='chat')),
    path('login/',login_view,name="login"),
    path('search/',account_search_view,name="search"),
    path('logout/',logout_view,name="logout"),
    path('register/',register_view,name="register"),
    path('',home_screen_view,name='home'), # name = 'home' is used for navigation on between or views in html page href="{% url 'home' %}"

     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

#create a new user
#create a superuser

class MyAccountManager(BaseUserManager):
	
	def create_user(self,email,username,password=None):
		if not email:
			raise ValueError("Users must have an email address")
		if not username:
			raise ValueError("User must have a username.")
		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user
	
	def create_superuser(self,email,username,password):
		user = self.create_user(
			email=self.normalize_email(email),
			username=username,
			password=password,
		)
		user.is_admin=True
		user.is_staff=True
		user.is_superuser=True
		user.save(using=self._db)
		return user

def get_profile_image_filepath(self,filename):
	return f'profile_images/{self.pk}/{"profile_image.png"}'

def get_default_profile_image():
	return "profile/def_prof_pic.png"

class Account(AbstractBaseUser):
	email			= models.EmailField(verbose_name="email",max_length=60,unique=True)
	username		= models.CharField(max_length=30,unique=True)
	date_joined		= models.DateTimeField(verbose_name="date joined",auto_now_add=True)
	last_login		= models.DateTimeField(verbose_name="last login",auto_now=True)
	is_admin 		= models.BooleanField(default=False)
	is_active		= models.BooleanField(default=True)
	is_superuser 	= models.BooleanField(default=False)
	is_staff 		= models.BooleanField(default=False)
	profile_image	= models.ImageField(max_length=255,upload_to=get_profile_image_filepath,null=True,blank=True,default=get_default_profile_image)
	hide_email		= models.BooleanField(default=True)

	objects		= MyAccountManager()

	USERNAME_FIELD 	= 'email'
	REQUIRED_FIELDS = ['username']



	def __str__(self):
		return self.username

	def has_perm(self,perm,obj=None):
		return self.is_admin

	def get_profile_image_filename(self):
		return str(self.profile_image)[str(self.profile_image).index(f'profile_images/{self.pk}/'):]

	def has_module_perms(self,app_label):
		return True

chat/models.py
from django.db import models
from django.conf import settings


class Message(models.Model):
	author		= models.ForeignKey(settings.AUTH_USER_MODEL,related_name="author",on_delete=models.CASCADE)
	content		= models.TextField()
	timestamp	= models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.author.username


class Chat(models.Model):
	participants		= models.ManyToManyField(settings.AUTH_USER_MODEL)
	messages			= models.ManyToManyField(Message,blank=True)
	is_group			= models.BooleanField(default=False)
	name        		= models.CharField(max_length=30,blank=True)
	admin				= models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name="group_admin") 

	def addMessage(self,message):
		self.messages.add(message)

	def addParticipant(self,user):
		if self.is_group or (not self.is_group and self.numberOfParticipant() < 2):
			self.participants.add(user)

	def removeParticipant(self,user):
		if user in self.participants.all():
			self.participants.remove(user)

	def deleteMessage(self,message):
		if message in self.messages.all():
			self.messages.remove(message)

	def getChatProfPicUrl(self,username):
		user = settings.AUTH_USER_MODEL.objects.get(username=username)
		if not self.is_group:
			if self.numberOfParticipant() == 2:
				receiver = self.participants.all().exclude(user=user)[0]
				return receiver.profile_image.url
		else:
			return "media/profile/def_prof_pic.png"

	def change_name(self,name):
		self.name = name
		self.save()

	def is_participant(self,user):
		if user in self.participants.all():
			return True
		return False


	def add_admin(self,user):
		if not user in self.admin.all():
			self.admin.add(user)


	def removeParticipant(self,user):
		self.participants.remove(user)

	def numberOfParticipant(self):
		return self.participants.all().count()

	def last_10_messages(self):
		return self.messages.all().order_by('-timestamp')[:10]

	def __str__(self):
		return str(self.pk)



# def get_profile_image_filepath(self,filename):
# 	return f'group_profile_images/{self.pk}/{"profile_image.png"}'

# def get_default_profile_image():
# 	return "group_profile_images/def_prof_pic.png"

# class Group(models.Model):
# 	chat 			= models.OneToOneField(Chat,on_delete=models.CASCADE,related_name='chat')
# 	name        	= models.CharField(max_length=30,unique=False,blank=False)
# 	profile_image 	= models.ImageField(max_length=255,upload_to=get_profile_image_filepath,null=True,blank=True,default=get_default_profile_image)
# 	admin			= models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name="admin")

	# def add_admin(self,user):
	# 	if not user in self.admin.all():
	# 		self.admin.add(user)

# 	def __str__(self):
# 		return self.name

chat/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# from django.contrib import settings
import json

from account.models import Account
from friend.models import FriendList
from chat.models import Chat
# from django.contrib.auth import get_user_model

def room(request,*args,**kwargs):

	if not request.user.is_authenticated:
		return HttpResponse("For chat with friend you must be authenticated");
	
	sender_id = request.user.id

	chat_id = kwargs.get('chat_id')
	try:
		chat = Chat.objects.get(pk=chat_id)
	except Chat.DoesNotExist:
		return HttpResponse("Something went wrong !! This chat does not exist !!")

	group_name = chat.name

	is_group = chat.is_group
	print(is_group)
	print(chat.id)

	receiver = None

	if not is_group:
		if chat.numberOfParticipant() == 2:
			receiver = chat.participants.all().exclude(username=request.user.username)[0]
			if sender_id == receiver.id:
				return HttpResponse("Something went wrong")
		else:
			return HttpResponse("Something went wrong")


	friends = FriendList.objects.get(user=request.user).friends.all()
	# if not request.user in FriendList.objects.get(user=receiver).friends.all():
	# 	return HttpResponse("You must be friends to chat with "+receiver.username)

	room_name = str(chat_id)
	
	# if sender_id > receiver_id:
	# 	room_name = str(receiver_id)+"_"+str(sender_id)	#   pattern : minvalue_maxvalue

	# print(sender_id)
	# print(receiver_id)
	# print(room_name)

	# all_chat = Chat.objects.all()
	chat_list = []	# [(chat1,receiver_username),(chat2,receiver_username),.....]

	for chat in Chat.objects.all():
		for user in chat.participants.all():
			if user == request.user:
				if chat.numberOfParticipant() == 2 and (not chat.is_group):
					chat_list.append((chat,chat.participants.all().exclude(username=user.username)[0]))
				else:
					chat_list.append((chat,False))


	# return HttpResponse("helllo world "+str(sender_id) +" "+ str(receiver_id))
	return render(request,'chat/chat.html',{
		'room_name':room_name,
		'receiver':receiver,
		'chat_list' : chat_list,
		'chat_id' : chat_id,
		'group_name' : group_name,
		'friends' : friends,
		})

def private_chat(request,receiver_id):
	user = request.user

	try:
		receiver = Account.objects.get(pk=receiver_id)
	except Account.DoesNotExist:
		return HttpResponse("Something went wrong !! Account does not exist ")

	receiver_friend_list = FriendList.objects.get(user=receiver)

	if not user in receiver_friend_list.friends.all():
		return HttpResponse("Something went wrong !! You must be friend with "+receiver.user.username)

	chat_id = None

	print(receiver)

	for chat in Chat.objects.all():
		if not chat.is_group:
			# print(chat.numberOfParticipant())
			if chat.numberOfParticipant() == 2:
				if (receiver in chat.participants.all()) and (request.user in chat.participants.all()):
						chat_id = chat.id

	if chat_id == None:
		chat = Chat.objects.create()
		chat.addParticipant(user)
		chat.addParticipant(receiver)
		chat.is_group = True
		chat_id = chat.id

	print(receiver.username+ " : "+str(chat_id))

	return redirect("chat:room",chat_id=chat_id)


def create_group(request):
	payload = {}
	user = request.user

	if request.method == "POST" and user.is_authenticated:
		try:
			print(request.POST.getlist('usernames[]'))
			username_list = request.POST.getlist('usernames[]')
			group_name = request.POST.get('group_name')
			# print("username list :"+username_list)
		
			chat = Chat.objects.create()
			chat.addParticipant(user)
			chat.add_admin(user)
			chat.name = group_name
			chat.is_group = True
			chat_id = chat.id
			chat.save()

			user_friend_list = FriendList.objects.get(user=user)

			for username in username_list:
				try:
					participant = Account.objects.get(username=username)
					if not participant in user_friend_list.friends.all():
						continue
				except Account.DoesNotExitst:
					continue

				if chat_id:
					chat.addParticipant(participant)

			payload['chat_id'] = chat_id
			payload['result'] = "success";

			print(chat.is_group)
			print(chat.id)

		except Exception as e:
			payload['result'] = "error"
			payload['exception'] = str(e)


	return HttpResponse(json.dumps(payload),content_type="application/json")

def group_view(request,*args,**kwargs):
	context = {}

	chat_id = kwargs.get('chat_id')
	
	

	if not request.user.is_authenticated:
		return redirect("login")
	try:
		chat = Chat.objects.get(pk=chat_id)
	except Chat.DoesNotExist:
		return HttpResponse("Something went wrong !! chat does not exist")

	if not chat.is_group:
		return HttpResponse("Something went wrong")

	context['chat'] = chat
	context['admins'] = chat.admin.all()

	participants = chat.participants.all()

	context['participants'] = participants

	return render(request,'chat/group.html',context)

chat/templates/chat/group.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	


<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
	}
	
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
		
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="logo" id="id_profile_image" src="{% static 'images/profiles/prof_1.png' %}">
		  		</div>
		  		
		  		<!-- <p class="mt-4 mb-1 field-heading">Admin</p>
		  		<h5>admin</h5> -->
		  		<p class="mt-4 mb-1 field-heading">Group Name</p>
		  		<h5><a href="{% url 'chat:room' chat_id=chat.id %}">{{chat.name}}</a></h5>

		  		<!-- If Auth user is viewing their own profile -->
		  		<!-- {% if request.user in admins %}
		  			<a  class="mt-4 btn btn-primary" href="#">Update</a>
				{% endif %} -->
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center participant-container">
					<ul>
						<li>
					  		<div class="select-title">
					  			<!-- <div class="arrow" onclick="">&larr;</div> -->
					  			<div>Participants</div>
					  			<!-- <div class="create-btn" onclick=""><i class="material-icons" style="color:white" onclick="">send</i></div> -->
					  		</div>
						</li>
						{% for participant in participants %}
						<li>
					  		<div class="participant" onclick="">
					  			<img src="{{participant.profile_image.url}}"/>
					  			{% if request.user == participant %}
					  				<div>
					  					<a href="{% url 'account:view' user_id=participant.id %}" class="user-name">You</a>
					  				</div>
					  			{% else %}
						  			<div>
						  				<a href="{% url 'account:view' user_id=participant.id %}" class="user-name">{{participant.username}}</a>
						  			</div>
					  			{% endif %}
					  		</div>
						</li>
						{% endfor %}

						<li>
					  		<div class="select-title">
					  			<!-- <div class="arrow" onclick="">&larr;</div> -->
					  			<div>Admins</div>
					  			<!-- <div class="create-btn" onclick=""><i class="material-icons" style="color:white" onclick="">send</i></div> -->
					  		</div>
						</li>
						{% for admin in admins %}
						<li>
					  		<div class="participant" onclick="">
					  			<img src="{{admin.profile_image.url}}"/>
					  			{% if request.user == admin %}
					  				<div>
					  					<a href="{% url 'account:view' user_id=admin.id %}" class="user-name">You</a>
					  				</div>
					  			{% else %}
						  			<div>
						  				<a href="{% url 'account:view' user_id=admin.id %}" class="user-name">{{admin.username}}</a>
						  			</div>
					  			{% endif %}
					  		</div>
						</li>
					

						{% endfor %}
					

					</ul>
				</div>

				

			</div>
		
		</div>
		{% endif %}

		
	</div>
</div>
<style type="text/css">
	.material-icons {
		   color: blue;
	}
	.participant{

	}





ul {
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.participant-container ul li {
  border-bottom: 1px solid #002c08;
  border-top: 1px solid #002c08;
  margin-top: -1px; /* Prevent double borders */
  background-color: #0048aa;
  /*padding: 6px;*/
  color: white;
  text-decoration: none;
  font-size: 18px;
  display: block;
  position: relative;
}

.participant-container ul li a{
	color: white;
}


.participant-container ul li:hover {
  background-color: #002c88;
}

.participant-container {
	max-height: 73vh;
  	overflow-y: scroll;
}

.participant {
  cursor: pointer;
  position: relative;
  width: 100%;
  min-width: 200px;
  display: flex;
  flex-direction: row;
  padding: 6px 8px;
  
  }

  .select-title{
  position: relative;
  width: 100%;
  background: #002c88;
  display: flex;
  flex-direction: row;
  padding: 10px 8px;
  justify-content: space-between;
  }

  .create-btn{
  	cursor: pointer;
  }

  .arrow{
  	margin-left: 5px;
    font-size: 18px;
    font-weight: bolder;
    width: 27px;
    cursor: pointer;
  }

  

 
  .participant > img{
  	width: 40px;
	height: 40px;
	border-radius: 100%;
  }

  .participant > div {
    padding: 7px 20px;
  }


</style>


<script type="text/javascript">
	
</script>
























	<!-- <div>
		
		<div class="container">
			<div class="row">
				<div class="col-7">
					<div class="col-12 image-container">
						
					</div>
					<div class="col-12">
						
					</div>
					{{chat_id}}
				</div>
				<div class="col-1">
					{{chat_id}}
				</div>
				<div class="col-4">
					{{chat_id}}
				</div>
			</div>
		</div>
	</div>

	<style type="text/css">
		
		.row > div {
			background-color: white;
		}
		.col-1{
			background-color: transparent !important;
		}
		.row{
			padding: 10px;
			width: 60vw;
			border: 1px solid blue;
			/*background-color: white;*/
			border-radius: 10px;
		}
		.container{
			display: flex;
		    flex-direction: row;
		    padding: 16px 24px;
		    
		    border-radius: 10px;
		    place-content: center;
		}
	</style> -->


{% endblock content %}